### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ghost** [odestcj/sgd-slam#1]
Thanks for publishing this project. This is the only javascript implementation of SLAM I've been able to find. Would you consider releasing this code under an open source license? I usually release my own projects under permissive licenses such as MIT, BSD, or public domain because that maximizes compatibility with upstream licenses people might want to use, such as GPL.

If the licensing question is sorted, I would like to adapt the code in this project to release as a reusable library published to [npm](https://npmjs.com), a popular package manager for javascript. Thanks.

**Comment by odestcj** [comment]
My pleasure.  Thanks for checking it out.

I just added the MIT license.  So, feel free to use and build on this very hastily written code.

I should also say this is mostly a simple adaptation of the algorithm listing from Olson's paper.  It should be relatively easy to reimplement from the paper, probably with better coding style and placement of sensor data (such as laser range) at each pose.  There is one notable missing element: the front-end for detecting loop closures.  Loop closures are currently hardcoded for the purpose of the example.  Ideally, these would be detected through some combination of nearest neighbors, scan matching, iterative closest point registration, etc.  For this purpose, it has been on my stack to reimplement Olson's max-mixture paper (http://www.roboticsproceedings.org/rss08/p40.pdf) with some reasonable matching heuristic.
